### ISSUE TITLE
style: get social profiles

### ISSUE THREAD

**Issue by srizvi** [yocxo/studio#201]
Please grab the `supyocxo` social profiles:

```
Yo CXO is a top Upwork agency. We help founders, startups, and fast-growing businesses achieve the outcomes they need to build products that people love. 🔥
```

If needed, shared email is: `sup@yocxo.com`. (Not for registering the accounts of course)

- LinkedIn
- Facebook
- Instagram
- TikTok
- Pinterest
- Mastodon

I will get Reddit and Youtube.

**Comment by rradice13** [comment]
All set.

If @ambi-dar can get covers done / get me the logo - I can get all of these updated.

Added Ambreen as admin to LI and FB. Put all other creds in Keeper.

- https://www.linkedin.com/company/supyocxo/ 
- https://facebook.com/supyocxo
- supyocxos (supyocxo) is taken on X, we can change to whatever works best
- supyocxo - TikTok
- supyocxo - Pinterest
- supyocxo - Mastadon

**Comment by srizvi** [comment]
You got `@supyocxo` yesterday. Thanks.
