### ISSUE TITLE
style: update hero team graphic

### ISSUE THREAD

**Issue by srizvi** [yocxo/studio#58]
I think we'll move to a more modern yet retro (minimal) vibe. Like axiomfm and or vercel. We'll be moving to neumorphic components.

Right now was experimenting with a bunch of styles, gradients etc. Pick/update according to requirements then iterate.

**Comment by ambi-dar** [comment]
I've made[ two options here that](https://www.canva.com/design/DAF9BgBl_eU/QASuHJpcCl3vN2Q5LLVSzA/edit) follow the neumorphic style

Let me know what you think and if it looks good on the page. put a dark background to check, looked good to me

**Comment by ambi-dar** [comment]
![6](https://github.com/sambi-dev/sambi/assets/45929546/32ecb817-87bf-40df-a3ff-d08818f3fc6c)
![5](https://github.com/sambi-dev/sambi/assets/45929546/a429fa54-5673-4d47-91cd-c678661d3425)
![4](https://github.com/sambi-dev/sambi/assets/45929546/979ee144-f2e0-445d-a8b3-ad9f1f824837)


@srizvi I'm working on these options, LMK if there's a direction you prefer. I used the darker background from the website as a background to get an idea of what it'll look like. Does it stay the same or shall I create one for light mode?

**Comment by srizvi** [comment]
You're focused on the framing, I mean the whole image itself including the characters which are so 2022.

I need to hear "I love it" then it doesn't matter what I think.
