### ISSUE TITLE
style: update how we roll illustrations

### ISSUE THREAD

**Issue by srizvi** [yocxo/studio#59]
See #58 for requirements.

Choose appropriate styles for global update then apply accordingly. Each should reinforce the copy messaging, visually.

Prefer SVG if possible.

**Comment by ambi-dar** [comment]
@srizvi please share access to canva file for this

**Comment by srizvi** [comment]
You made them

**Comment by ambi-dar** [comment]
Yes, I meant the gradients, but I remembered you made those on the website, I've made [edits to the designs here](https://www.canva.com/design/DAF-vt0LLcU/J-1IHRGm15aixNQKy6b9YQ/edit)

IMO this section looks good, passing on legos needs to be updated.
